name: packages
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
  # Dry-run only
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

env:
  PYTHON_VERSION: "3.10"
  PACKAGE: "intake-dremio"

jobs:
  waiting_room:
    name: Waiting Room
    runs-on: ubuntu-latest
    needs: [conda_build, pip_install]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - run: echo "All builds have finished, have been approved, and ready to publish"

  conda_build:
    name: Build Conda
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: ${{ env.PYTHON_VERSION }}
      - name: conda setup
        run: |
          conda install -y conda-build python-build
      - name: conda build
        run: |
          source ./scripts/conda-build.sh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: conda
          path: dist/*.tar.bz2
          if-no-files-found: error

  conda_publish:
    name: Publish Conda
    runs-on: ubuntu-latest
    needs: [conda_build, waiting_room]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: conda
          path: dist/
      - name: Set environment variables
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "CONDA_FILE=$(ls dist/*.tar.bz2)" >> $GITHUB_ENV
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
      - name: conda setup
        run: |
          conda install -y anaconda-client
      - name: conda dev upload
        if: contains(env.TAG, 'a') || contains(env.TAG, 'b') || contains(env.TAG, 'rc')
        run: |
          anaconda --token ${{ secrets.CONDA_UPLOAD_TOKEN }} upload --user pyviz --label=dev $CONDA_FILE
      - name: conda main upload
        if: (!(contains(env.TAG, 'a') || contains(env.TAG, 'b') || contains(env.TAG, 'rc')))
        run: |
          anaconda --token ${{ secrets.CONDA_UPLOAD_TOKEN }} upload --user pyviz --label=dev --label=main $CONDA_FILE

  pip_build:
    name: Build PyPI
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install build
        run: |
          python -m pip install build
      - name: Build package
        run: python -m build .
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pip
          path: dist/
          if-no-files-found: error

  pip_install:
    name: Install PyPI
    runs-on: "ubuntu-latest"
    needs: [pip_build]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/download-artifact@v4
        with:
          name: pip
          path: dist/
      - name: Install package
        run: python -m pip install dist/*.whl
      - name: Test package
        env:
          PACKAGE: "intake_dremio"
        run: python -c "import $PACKAGE; print($PACKAGE.__version__)"

  pip_publish:
    name: Publish PyPI
    runs-on: ubuntu-latest
    needs: [pip_build, waiting_room]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pip
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PPU }}
          password: ${{ secrets.PPP }}
          repository-url: "https://upload.pypi.org/legacy/"
